name: rv_hdesk
recipe: laravel
config:
  webroot: public
  config:
  php: 8.1
  composer_version: 2-latest
  run:
      - composer install
      - cp .env.example .env
      - php artisan RV:setup
      - php artisan RV:demo-data
  node:
    type: node:16
    build:
      - yarn
  via: nginx:1.18
  app_mount: delegated
  database: mysql:8.0
services:
  nodejs:
    type: node:16
    command: npm start
    build_as_root:
      - npm install
      - npm run dev
  appserver:
    build_as_root:
      - composer install
      - cp .env.example .env
      - php artisan RV:setup
      - php artisan RV:demo-data
