name: rv_hdesk
recipe: laravel
config:
  webroot: public
  config:
  php: 8.1
  composer_version: 2-latest
  run:
      - composer install
  node:
    type: node:16
    build:
      - yarn
  via: nginx:1.18
  app_mount: delegated
  database: mysql:8.0
  run_as_root:
      - echo "127.0.0.1 rv_hdesk.lndo.site" >> /etc/hosts
