name: rv_hdesk
recipe: laravel
config:
  webroot: public
  config:
  php: 8.1
  composer_version: 2-latest
  run:
      - composer install
  node:
    type: node:16
    build:
      - yarn
  via: nginx:1.18
  app_mount: delegated
  database: mysql:8.0
services:
  nodejs:
    type: node:16
    command: npm start

